# Weaver semantic-conventions gate (additive; GEN-R09 block-vs-degrade)
#
# Usage in devenv.nix:
#   imports = [ (inputs.effect-utils.devenvModules.tasks.weaver {}) ];
#
# Provides: weaver:check
#
# Runs `weaver registry check` over the ACTUALLY-EMITTED registry
# (genie/weaver-registry/, generated by genie), resolving the pinned upstream OTel semconv
# dependency HERMETICALLY against a local Nix FOD (`nix/weaver-flake#semconv-model`, v1.44.0).
# Stable policy mode keeps upstream `definition/2` files as warnings; `--future` promotes the
# tagged upstream registry's own experimental files to errors.
#
# Block-vs-degrade (GEN-R09): a weaver VALIDATION failure (check exits nonzero) BLOCKS. Weaver
# UNAVAILABILITY (flake build/eval failure, binary missing) DEGRADES to a warning and exits 0,
# so a broken toolchain never wedges unrelated work — the two are handled in separate lanes.
{
  # Repo-relative path to the emitted registry directory.
  registryDir ? "genie/weaver-registry",
  # Path flake ref (relative to repo root) exposing `#weaver` and `#semconv-model`.
  weaverFlake ? "nix/weaver-flake",
}:
{ lib, pkgs, ... }:
let
  trace = import ../lib/trace.nix { inherit lib; };
in
{
  tasks = {
    "weaver:check" = {
      description = "Validate the emitted Weaver registry (additive gate; degrades if weaver is unavailable)";
      exec = trace.exec "weaver:check" ''
        set -uo pipefail
        root="''${DEVENV_ROOT:-$PWD}"
        reg="$root/${registryDir}"
        flake="$root/${weaverFlake}"

        if [ ! -f "$reg/manifest.yaml" ]; then
          echo "✗ weaver:check: $reg/manifest.yaml not found — run 'genie:run' first" >&2
          exit 1
        fi

        # --- LANE 1: availability (degrade to a warning; must NOT wedge the main check) ---
        weaver_err="$(${pkgs.coreutils}/bin/mktemp)"
        if ! weaver_pkg="$(${pkgs.nix}/bin/nix build --no-link --print-out-paths "$flake#weaver" 2>"$weaver_err")"; then
          echo "⚠ weaver:check DEGRADED: could not build the weaver flake ($flake#weaver) — skipping (exit 0)." >&2
          ${pkgs.coreutils}/bin/cat "$weaver_err" >&2 || true
          exit 0
        fi
        if ! model="$(${pkgs.nix}/bin/nix build --no-link --print-out-paths "$flake#semconv-model" 2>"$weaver_err")"; then
          echo "⚠ weaver:check DEGRADED: could not materialize the upstream semconv FOD ($flake#semconv-model) — skipping (exit 0)." >&2
          ${pkgs.coreutils}/bin/cat "$weaver_err" >&2 || true
          exit 0
        fi
        if [ ! -x "$weaver_pkg/bin/weaver" ]; then
          echo "⚠ weaver:check DEGRADED: weaver binary missing at $weaver_pkg/bin/weaver — skipping (exit 0)." >&2
          exit 0
        fi

        # --- LANE 2: validation (BLOCKS on failure) ---
        # Copy the emitted registry to a scratch dir and rewrite the upstream dependency to the
        # hermetic local FOD path. The committed manifest keeps the portable git-URL form; this
        # rewrite makes the gate fully offline/deterministic without touching tracked files.
        tmp="$(${pkgs.coreutils}/bin/mktemp -d)"
        trap '${pkgs.coreutils}/bin/rm -rf "$tmp"' EXIT
        # Copy ALL emitted YAML (manifest + the single collapsed attributes.yaml + signals.yaml).
        # A former `*.attributes.yaml` glob would NOT match the collapsed 15-char `attributes.yaml`.
        ${pkgs.coreutils}/bin/cp "$reg"/*.yaml "$tmp/"
        ${pkgs.coreutils}/bin/chmod -R u+w "$tmp"
        ${pkgs.gnused}/bin/sed -i "s|registry_path: .*|registry_path: $model|" "$tmp/manifest.yaml"

        echo "weaver:check: validating $reg against upstream $model"
        "$weaver_pkg/bin/weaver" registry check -r "$tmp"
      '';
    };
  };
}
